### ISSUE TITLE
Evolve the Indy SDK from a monolith to a series of separate components suitable for Aries consumption

### ISSUE THREAD

**Issue by swcurran** [bcgov/von#332]
The work on this epic includes:

- [ ] indy-vdr to provide an interface with the ledger; embeddable or for use as a proxy
- [ ] indy-credx to wrap the anoncreds functionality exposed by Ursa
- [ ] indy-shared-rs to provide shared utilities to other Indy components
- [ ] aries-storage (or something similar) to include lox, KMS and other agent storage
- [ ] aries-vdri to provide an interface from aries to a variety of ledgers
- [ ] aries-shared-rs to provide shared utilities for other Aries components
