### ISSUE TITLE
Migrate demo issuer services to Sovrin StagingNet

### ISSUE THREAD

**Issue by esune** [bcgov/von#334]
To promote interoperability, we want to migrate our demo issuing services to the Sovrin StagingNet.

The services that will be migrated are:
- [ ] email-verification-service
- [ ] conf-book
- [ ] unverified person issuer
- [ ] healthbc issuer (PROD)
- [ ] esr1 issuer (PROD)
- [ ] esr2 issuer (PROD)
- [ ] medlab issuer (PROD)
- [ ] safe entry verifier service (PROD)
- [ ] safe entry c19 verifier service (PROD)
- [ ] a new instance of `vc-authn` connected to Sovrin StagingNet should be deployed as well.

**Tasks:**
- [ ] register DIDs of existing agents on StagingNet
- [ ] switch agents to using StagingNet
- [ ] deploy `vc-authn` instance pointing to StagingNet (use `devex-con-prod` namespace)
- [ ] update `vc-authn` configurations with the appropriate clients for the PROD apps
- [ ] add proof-request configurations for PROD apps to `vc-authn`
- [ ] update `config.json` for the PROD apps to use the new `vc-authn` endpoint for authentication

**Comment by WadeBarnes** [comment]
@esune, I think this is now a duplicate of https://github.com/bcgov/von/issues/341.

**Comment by esune** [comment]
@WadeBarnes you are right. #341 is better structured and more detailed, I will close this issue and use the other one to track the work.
